apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-content
data:
  index.html: |
    <!doctype html>
    <html>
    <head>
    <meta charset=utf-8>
    <title>Welcome to the Sample SimpleApp!</title>
    </head>
    <body>
    <h1>Welcome to the Sample SimpleApp</h1>
    <div><p>This is a really SimpleApp.</p></div>
    </body>
    </html>
---
apiVersion: apps.raulpedroche.es/v1alpha1
kind: SimpleApp
metadata:
  name: sample
spec:
  image: nginx:latest
  ports:
    - name: http
      hostPort: 80
      containerPort: 80
  replicas: 3
  env:
    - name: ENV_VAR
      value: "value"
  volumes:
    - mountPath: /usr/share/nginx/html
      configMap:
        defaultMode: 0o0644
        name: sample-content
